REFRESH MATERIALIZED VIEW CONCURRENTLY derped_global_images;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_global_comments;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_global_topics;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_global_posts;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_global_faves;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_global_votes;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_global_taggings;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_global_tag_changes;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_global_source_changes;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_global_reports;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_user_visits;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_user_images;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_user_comments;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_user_topics;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_user_posts;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_user_faves;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_user_votes;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_user_tag_changes;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_user_source_changes;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_user_reports;

REFRESH MATERIALIZED VIEW CONCURRENTLY derped_faved_tags;